# Intelligibility Data Processing

# Author: Micah E. Hirsch, mhirsch@fsu.edu

# Date: 10/25/2023

## Purpose: To load in transcriptions of the listener responses,
## determine phrase recognition accuracy, and merge with the pupil data.
## This particular data processing and analysis is being completed for a
## poster presentation at the Annual American Speech Language Hearing 
## Association Convention being held in Boston, MA in November 2023.

# Loading required packages

library(rio) # install.packages("rio")
library(tidyverse) # install.packages("tidyverse")
# Remotes is needed to download autoscore
library(remotes) # install.packages("remotes")
library(autoscore) # remotes::install_github("autoscore/autoscore")
library(SnowballC) # install.packages("SnowballC")

# Set working directory to load data

setwd("~/Documents/Listening-Effort-in-Dysarthria/Raw Data")

# Load in data

transcriptions <- rio::import("transcriptions.csv", header = T)

# Preparing the script for scoring

transcriptions <- transcriptions %>%
  # Removing unneeded columns generated by Qualtrics
  dplyr::select(!c(StartDate:RA, Time, Counter_List)) %>%
  # Removing first two rows
  dplyr::filter(grepl("LE", ID)) %>%
  dplyr::filter(!grepl("Participant", ID)) %>%
  # LE01 has multiple submissions. Only keeping the completed submission.
  dplyr::filter(`85` != "") %>%
  # converting df to long format
  tidyr::pivot_longer(cols = "1":"85",
                      names_to = "trial",
                      values_to = "response") %>%
  dplyr::rename(id = ID) %>%
  dplyr::mutate(trial = as.numeric(trial))

# Calculating phrase accuracy 

## Set working directory to location of cleaned pupil data

setwd("~/Documents/Listening-Effort-in-Dysarthria/ASHA 2023 Analysis/Cleaned Data")

pupil <- rio::import("cleaned_pupil_data.csv")

## Extract phrase targets from pupil df

targets <- pupil %>%
  dplyr::rename(id = subject,
                target = targetphrase) %>%
  dplyr::select(id, trial, target) %>%
  distinct()
  
## Merging transcription and target dfs

phrase_acc <- targets %>%
  dplyr::left_join(transcriptions, by = c("id", "trial")) %>%
  ## Count number of words in target phrase
  dplyr::mutate(target_number = str_count(target, "\\S+")) 

## Counting number of correctly recognized words

phrase_acc <- autoscore::autoscore(
  phrase_acc,
  acceptable_df = autoscore::acceptable_spellings,
  plural_rule = T,
  plural_add_rule = T,
  tense_rule = T,
  tense_add_rule = T,
  a_the_rule = T,
  double_letter_rule = T) %>%
  dplyr::rename(., correct_words = autoscore)

# Creating dichotomous phrase repetition accuracy variable

phrase_acc <- phrase_acc %>%
  dplyr::mutate(rep_acc = ifelse(target_number == correct_words, "accurate", "inaccurate")) %>%
  dplyr::rename(subject = id,
                targetphrase = target)

# Merge phrase accuracy back with the rest of the pupil data

cleaned_data <- pupil %>%
  dplyr::left_join(phrase_acc, by = c("subject", "trial", "targetphrase"))

# Removing unneeded items from the environment

rm(phrase_acc, pupil, targets, transcriptions)

# Export csv file of cleaned data

rio::export(cleaned_data, "cleaned_data.csv")
