# Intelligibility Data Processing

# Author: Micah E. Hirsch, mhirsch@fsu.edu

# Date: 10/24/2023

## Purpose: To load in transcriptions of the listener responses,
## determine phrase recognition accuracy, and merge with the pupil data.
## This particular data processing and analysis is being completed for a
## poster presentation at the Annual American Speech Language Hearing 
## Association Convention being held in Boston, MA in November 2023.

# Loading required packages

library(rio) # install.packages("rio")
library(tidyverse) # install.packages("tidyverse")
# Remotes is needed to download autoscore
library(remotes) # install.packages("remotes")
library(autoscore) # remotes::install_github("autoscore/autoscore")
library(SnowballC) # install.packages("SnowballC")

# Set working directory to load data

setwd("~/Documents/Listening-Effort-in-Dysarthria/Raw Data")

# Load in data

transcriptions <- rio::import("transcriptions.csv", header = T)

# Preparing the script for scoring

transcriptions <- transcriptions %>%
  # Removing unneeded columns generated by Qualtrics
  dplyr::select(!c(StartDate:RA, Time, Counter_List)) %>%
  # Removing first two rows
  dplyr::filter(grepl("LE", ID)) %>%
  dplyr::filter(!grepl("Participant", ID)) %>%
  # LE01 has multiple submissions. Only keeping the completed submission.
  dplyr::filter(`85` != "") %>%
  # converting df to long format
  tidyr::pivot_longer(cols = "1":"85",
                      names_to = "trial",
                      values_to = "response") %>%
  dplyr::rename(id = ID) %>%
  dplyr::mutate(trial = as.numeric(trial))



