# Intelligibility Data Preprocessing

# Author: Micah E. Hirsch

# Date: 8/28/23 
# Current Version - Pilot Data

## Purpose: To load in transcriptions of listener responses, 
## determine phrase recognition accuracy, and to merge with the pupil data.

## Note: This script is a work-in-progress

# Loading Required Packages

library(rio) # install.packages("rio")
library(tidyverse) # install.packages("tidyverse")
# Remotes is needed to install autoscore
library(remotes) # install.packages("autoscore")
library(autoscore) # remotes::install_github("autoscore/autoscore")
library(SnowballC) # install.packages("SnowballC)

# Load in transcription data

## Set working directory to raw transcription csv file
setwd("~/Documents/Listening-Effort-in-Dysarthria/Data Preprocessing/Raw Data")

## Load in transcription data
transcriptions <- rio::import("transcriptions.csv", header = T)

# Preparing the script for scoring

transcriptions <- transcriptions %>%
  # Removing unneeded columns generated by Qualtrics
  dplyr::select(!c(StartDate:RA, Time, Counter_List)) %>%
  # Removing first two rows
  dplyr::filter(grepl("LE", ID)) %>%
  dplyr::filter(!grepl("Participant", ID)) %>%
  # LE01 has multiple submissions. Only keeping the completed submission.
  dplyr::filter(`85` != "") %>%
  # converting df to long format
  tidyr::pivot_longer(cols = "1":"85",
                      names_to = "trial",
                      values_to = "response") %>%
  dplyr::rename(id = ID) %>%
  dplyr::mutate(trial = as.numeric(trial))

# Load in cleaned pupil data

pupil <- rio::import("cleaned_pupil_data.csv")

targets <- pupil %>%
  dplyr::rename(id = subject,
                target = targetphrase) %>%
  dplyr::select(id, trial, target) %>%
  distinct()

# Merging listener responses with pupil data

data <- targets %>%
  dplyr::left_join(transcriptions, by = c("id", "trial"))

# Count number of words in target phrase

data <- data %>%
  dplyr::mutate(target_number = str_count(target, "\\S+"))

# Counting correct number of words using Autoscore

data <- autoscore::autoscore(
  data,
  acceptable_df = autoscore::acceptable_spellings,
  plural_rule = T,
  plural_add_rule = T,
  tense_rule = T,
  tense_add_rule = T,
  a_the_rule = T,
  double_letter_rule = T) %>%
  dplyr::rename(., correct_words = autoscore)

# Creating dichotomous repetition accuracy variable

data <- data %>%
  dplyr::mutate(rep_acc = ifelse(target_number == correct_words, "accurate", "inaccurate")) %>%
  dplyr::rename(subject = id,
                targetphrase = target)

# Merge back with the rest of the pupil data

cleaned_data <- pupil %>%
  dplyr::left_join(data, by = c("subject", "trial", "targetphrase"))

# Remove unneeded items from the environment

rm(data, pupil, targets, transcriptions)

# Export csv (7/27/23: Pilot Data)

## Setting working directory

setwd("~/Documents/Listening-Effort-in-Dysarthria/Cleaned Data")

rio::export(cleaned_data, "cleaned_data.csv")
