---
title: "Listening Effort MSC Analysis"
author: "Micah E. Hirsch"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

This analysis was conducted using R version 4.3.1

```{r, echo = F, warning = F, message = F}

# Load Needed Packages
library(rio) # install.packages("rio")
library(tidyverse) # install.packages("tidyverse")
# Need remotes package to install gazer and saccades
library(remotes) # install.packages("remotes")
library(gazer) # remotes::install_github("dmirman/gazer")
library(saccades) # remotes::install_github("tmalsburg/saccades/saccades")
library(zoo) # install.packages("zoo")
library(ggpubr) # installl.packages("ggpubr")
library(gt) # install.packages("gt")
library(gtsummary) # install.packages("gtsummary")
library(glmmTMB) # install.packages("glmmTMB")
library(performance) # install.packages("performance")
library(sjPlot) # install.packages("sjPlot")
library(ggridges) # install.packages("ggridges")
library(lme4) # install.packages("lme4")
library(lmerTest) # install.packages("lmerTest")
library(optimx) # install.packages("optimx")

```


# Listener Demographics


```{r}

listener_demo <- rio::import("Cleaned Data/cleaned_listener_demo.csv") |>
  dplyr::mutate(gender = factor(gender, levels = c("Man", "Woman", "Nonbinary", "Questioning", "Prefer not to answer")),
                ethnicity = factor(ethnicity, levels = c("Hispanic/Latino(a/e)", "Not Hispanic/Latino(a/e)", "Prefer not to answer")),
                race = factor(race, levels = c("white/Caucasian", "Black/African American", "Asian/Asian American",
                                               "Native Hawaiian or Other Pacific Islander", "Native American or Alaska Native",
                                               "Biracial or Multiracial", "Prefer not to answer", "Race not listed")),
                native_lang = factor(native_lang, c("American English", "Not American English")))
  
demo_table <- listener_demo |>
  dplyr::select(age, gender, ethnicity, race, native_lang) |>
  tbl_summary(type = list(age ~ "continuous",
                          gender ~ "categorical",
                          ethnicity ~ "categorical",
                          race ~ "categorical",
                          native_lang ~ "categorical"),
              statistic = list(all_continuous() ~ "{mean} ({sd}, {min}-{max})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(everything() ~ c(2)),
              label = list(age ~ "Age",
                           gender ~ "Gender",
                           ethnicity ~ "Ethnicity",
                           race ~ "Race",
                           native_lang ~ "Native Language")) |>
  as_gt()

demo_table

demo_table |>
  gt::gtsave("Tables/demo_tabe.html")

```

```{r}

rm(demo_table, listener_demo)

```

# Speaker Intelligibility and Phrase Accuracy

## Mean Speaker Intelligibility

```{r}

data <- rio::import("Cleaned Data/cleaned_data_normed.csv") |>
  # removing trials with missing rep accuracy
  dplyr::mutate(rep_acc = ifelse(rep_acc == "", NA, rep_acc)) |>
  dplyr::filter(!is.na(rep_acc)) |>
  dplyr::mutate(speaker = factor(speaker, levels = c("Control", "ALS")),
                trial_c = trial - 6,
                rep_acc = factor(rep_acc, levels = c("accurate", "inaccurate")))

speaker_acc <- data |>
  dplyr::select(subject, trial, speaker, correct_words, target_number, rep_acc) |>
  dplyr::distinct() |>
  dplyr::mutate(intel = (correct_words/target_number)*100) |>
  dplyr::select(-c(subject, trial, correct_words, target_number)) |>
  tbl_summary(by = speaker,
              type = list(intel ~ "continuous",
                          rep_acc ~ "categorical"),
              statistic = list(all_continuous() ~ "{mean} ({sd})",
                               all_categorical() ~ "{n} ({p}%)"),
              digits = list(everything() ~ c(2)),
              label = list(intel ~ "Intelligibility",
                           rep_acc ~ "Repetition Accuracy")) |>
  as_gt()

speaker_acc

speaker_acc |>
  gt::gtsave("Tables/speaker_intel.html")

```

